#!/usr/bin/env python3
"""
Local runner for the Azure Access Review.

Why this exists: brand-new Azure subscriptions often have zero quota for
Functions Consumption Plan and Azure OpenAI deployments. Quota requests take
1-3 business days. This script bypasses both: runs the same findings logic
locally using your `az login` credentials, generates a CSV report, and emails
it via Gmail SMTP. No deployed infrastructure required.

Usage:
    # Set env vars (or put in a .env file)
    export GMAIL_USER="abdiemohamed.tech@gmail.com"
    export GMAIL_APP_PASSWORD="xxxx xxxx xxxx xxxx"   # Gmail app password
    export AZURE_SUBSCRIPTION_ID="e2b8d746-..."        # your subscription
    export RECIPIENT_EMAIL="abdiemohamed.tech@gmail.com"

    # Run
    python3 scripts/run_local.py
"""

import csv
import io
import os
import smtplib
import sys
from datetime import datetime, timezone
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

# Make sure src/function modules are importable when run from project root.
SCRIPT_DIR = Path(__file__).resolve().parent
SRC_DIR = SCRIPT_DIR.parent / "src" / "function"
sys.path.insert(0, str(SRC_DIR))

from findings.rbac_findings import collect_rbac_findings
from findings.defender_findings import collect_defender_findings
from findings.activity_log_findings import collect_activity_findings
from reporting import build_csv
from narrative import _fallback_summary  # template-based summary, no OpenAI needed


def main():
    # Required env vars
    subscription_id = require_env("AZURE_SUBSCRIPTION_ID")
    recipient = require_env("RECIPIENT_EMAIL")
    gmail_user = require_env("GMAIL_USER")
    gmail_pwd = require_env("GMAIL_APP_PASSWORD")

    print(f"Running access review for subscription {subscription_id}")
    print(f"Will email report to {recipient}")
    print()

    # Collect findings
    findings = []
    print("Collecting RBAC findings...")
    findings += collect_rbac_findings(subscription_id)
    print(f"  -> {sum(1 for f in findings if f['category'] == 'RBAC')} RBAC findings")

    print("Collecting Defender for Cloud findings...")
    findings += collect_defender_findings(subscription_id)
    print(f"  -> {sum(1 for f in findings if f['category'] == 'Defender')} Defender findings")

    print("Collecting Activity Log findings...")
    findings += collect_activity_findings(subscription_id)
    print(f"  -> {sum(1 for f in findings if f['category'] == 'ActivityLog')} Activity Log findings")

    print(f"\nTotal findings: {len(findings)}")

    # Build the CSV report
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    filename = f"azure-access-review-{timestamp}.csv"
    csv_buffer = build_csv(findings)
    csv_content = csv_buffer.getvalue()

    # Save a local copy as backup
    local_path = SCRIPT_DIR.parent / filename
    local_path.write_text(csv_content)
    print(f"Saved local copy: {local_path}")

    # Build the narrative (template-based, no AI required)
    narrative = _fallback_summary(findings)
    narrative = (
        "Azure Access Review report attached.\n\n"
        + narrative
        + "\n\n"
        + "This report was generated by run_local.py against your live Azure subscription. "
        + "The deployed Function App version (which uses Azure OpenAI for an AI-generated "
        + "narrative) is blocked pending Azure quota approval; this email uses a template "
        + "summary instead."
    )

    # Send via Gmail SMTP
    print(f"\nSending email via Gmail SMTP...")
    send_via_gmail_smtp(
        gmail_user=gmail_user,
        gmail_pwd=gmail_pwd,
        recipient=recipient,
        subject=f"Azure Access Review - {timestamp}",
        body=narrative,
        attachment_name=filename,
        attachment_content=csv_content,
    )
    print(f"Email sent to {recipient}")


def send_via_gmail_smtp(gmail_user, gmail_pwd, recipient, subject, body, attachment_name, attachment_content):
    """Send a multipart email with CSV attachment via Gmail SMTP."""
    msg = MIMEMultipart()
    msg["From"] = gmail_user
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    attachment = MIMEApplication(attachment_content.encode("utf-8"), _subtype="csv")
    attachment.add_header("Content-Disposition", "attachment", filename=attachment_name)
    msg.attach(attachment)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(gmail_user, gmail_pwd.replace(" ", ""))  # strip spaces from app pwd
        server.send_message(msg)


def require_env(name: str) -> str:
    val = os.environ.get(name)
    if not val:
        sys.stderr.write(f"Error: env var {name} is required.\n")
        sys.stderr.write("\nSet env vars before running:\n")
        sys.stderr.write("  export GMAIL_USER='you@gmail.com'\n")
        sys.stderr.write("  export GMAIL_APP_PASSWORD='xxxx xxxx xxxx xxxx'\n")
        sys.stderr.write("  export AZURE_SUBSCRIPTION_ID='<sub-id>'\n")
        sys.stderr.write("  export RECIPIENT_EMAIL='you@example.com'\n")
        sys.exit(1)
    return val


if __name__ == "__main__":
    main()
